# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sudo apt install openssh-server curl tmate

      # Runs a set of commands using the runners shell
      - name: setup sshd
        run: |
          echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
          echo $(curl ifconfig.co/ip) > /tmp/ip
          
          
      - name: Server Shell
        # You may pin to the exact commit or the version.
        # uses: tzzs/server-shell@e6313d235c16b3b51c67277ba2ec70a55e43c0d6
        uses: tzzs/server-shell@v3
        with:
          # server private key
#           PRIVATE_KEY: ''
          # server login username
          USERNAME: root
          # server ip
          IP: localhost
          # The port to connect to the server ssh
          PORT: 22 # optional, default is 22
          # shell to execute on server
          SHELL: /bin/bash # optional
